name: dependabot-bundler-conservative
description: Update Dependabot's pull request for bundler with `--conservative` option.
inputs:
  github-token:
    description: GitHub access token (See README for required permissions).
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        token: ${{ inputs.github_token }}
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: dependabot/fetch-metadata@v2
      id: metadata
      with:
        github-token: ${{ inputs.github_token }}
    - if: ${{ steps.metadata.outputs.package-ecosystem == 'bundler' }}
      uses: ruby/setup-ruby@v1
    - if: ${{ steps.metadata.outputs.package-ecosystem == 'bundler' }}
      run: |
        git checkout HEAD~ -- Gemfile.lock
        bundle lock --conservative --update "${{ steps.metadata.outputs.dependency-names }}"
      env:
        BUNDLE_FROZEN: "false"
      shell: bash
    - if: ${{ steps.metadata.outputs.package-ecosystem == 'bundler' }}
      uses: stefanzweifel/git-auto-commit-action@v6
branding:
  color: blue
  icon: git-pull-request
